// scripts/commons-targets.mjs — consultas por artigo (id -> queries de busca no Commons)
export const TARGETS = [
  { id: '31', queries: ['Nvidia GeForce graphics card', 'graphics card'] },
  { id: '32', queries: ['gaming computer RGB', 'gaming PC', 'personal computer case'] },
  { id: '33', queries: ['server room data center', 'data center'] },
  { id: '34', queries: ['silicon wafer semiconductor', 'microchip processor'] },
  { id: '35', queries: ['Nvidia graphics card', 'graphics card'] },
  { id: '36', queries: ['graphics card computer', 'computer gaming hardware'] },
  { id: '37', queries: ['computer monitor desk', 'computer monitor'] },
  { id: '38', queries: ['memory modules RAM', 'computer memory RAM'] },
  { id: '39', queries: ['smartphone social media apps', 'smartphone apps'] },
  { id: '40', queries: ['Microsoft headquarters', 'laptop computer work desk'] },
  { id: '41', queries: ['telescope observatory dome', 'observatory night'] },
  { id: '42', queries: ['Artemis 1 launch', 'Space Launch System rocket', 'full moon photography'] },
  { id: '43', queries: ['magnetic resonance imaging scanner', 'MRI hospital'] },
  { id: '44', queries: ['Lady Justice statue', 'scales of justice'] },
  { id: '45', queries: ['quantum computer', 'supercomputer'] },
  { id: '46', queries: ['5G antenna tower', 'cell tower'] },
  { id: '47', queries: ['Escherichia coli microscopy', 'bacteria culture petri dish'] },
  { id: '48', queries: ['CERN LHC tunnel', 'CERN'] },
  { id: '49', queries: ['game controller neon', 'gamepad'] },
  { id: '50', queries: ['data center servers', 'server room'] },
  { id: '51', queries: ['television remote control hand', 'watching television'] },
  { id: '52', queries: ['film camera set', 'cinema camera'] },
  { id: '53', queries: ['tablet computer reading ebook', 'ebook reader hand'] },
  { id: '54', queries: ['plasma globe', 'plasma ball'] },
  { id: '55', queries: ['deep sea jellyfish', 'deep sea fish'] },
  { id: '56', queries: ['nautilus shell spiral', 'ammonite fossil'] },
  { id: '57', queries: ['smartwatch hand', 'smartwatch'] },
  { id: '58', queries: ['tokamak', 'fusion reactor'] },
  { id: '59', queries: ['comic book shop', 'comic store'] },
  { id: '60', queries: ['Marvel comics shelf', 'comic book store interior'] },
  { id: '61', queries: ['movie theater auditorium', 'cinema auditorium'] },
  { id: '62', queries: ['comic book store', 'comic books shelf'] },
  { id: '63', queries: ['Superman cosplay', 'superhero cosplay'] },
  { id: '64', queries: ['Batman cosplay', 'city skyline night'] },
  { id: '65', queries: ['home cinema television', 'television screen'] },
  { id: '66', queries: ['empty office corridor', 'empty corridor'] },
  { id: '67', queries: ['milky way galaxy', 'starry night sky'] },
  { id: '68', queries: ['television remote control', 'watching tv'] },
  { id: '69', queries: ['abandoned hospital', 'abandoned corridor'] },
  { id: '70', queries: ['city skyline aerial night', 'city lights night aerial'] },
  { id: '71', queries: ['Disneyland castle', 'theme park castle'] },
  { id: '72', queries: ['Wadi Rum desert', 'desert dunes'] },
  { id: '73', queries: ['Disneyland fireworks', 'Disneyland park'] },
  { id: '74', queries: ['Miami skyline night', 'neon city night'] },
  { id: '75', queries: ['cosplay superhero', 'comic convention cosplay'] },
  { id: '76', queries: ['Alnwick Castle', 'medieval castle'] },
  { id: '77', queries: ['knight armour sword', 'medieval knight'] },
  { id: '78', queries: ['foggy street night', 'foggy town'] },
  { id: '79', queries: ['Orion Nebula', 'nebula space'] },
  { id: '80', queries: ['space shuttle launch', 'rocket launch'] },
  { id: '81', queries: ['aurora borealis green', 'aurora'] },
  { id: '82', queries: ['Manhattan skyline', 'New York skyline'] },
  { id: '83', queries: ['living room television', 'sofa tv'] },
  { id: '84', queries: ['Monument Valley', 'desert butte'] },
  { id: '85', queries: ['comic book shop shelf', 'comic books collection'] },
  { id: '86', queries: ['comic book store shelf', 'comic store'] },
  { id: '87', queries: ['comic convention cosplay group', 'comic con'] },
  { id: '88', queries: ['Bran Castle', 'gothic castle fog'] },
  { id: '89', queries: ['wargame miniatures tabletop', 'board game strategy chess', 'chessboard game'] },
  { id: '90', queries: ['foggy forest', 'misty forest'] },
  { id: '91', queries: ['Xbox Series X', 'Xbox console', 'video game console'] },
  { id: '92', queries: ['PlayStation 5', 'PlayStation console', 'video game console'] },
  { id: '93', queries: ['film studio lights', 'movie studio'] },
  { id: '94', queries: ['Mercury planet MESSENGER', 'Mercury planet'] },
  { id: '95', queries: ['integrated circuit macro photography', 'computer chip circuit board'] },
  { id: '96', queries: ['Saturn planet Cassini', 'Saturn planet'] },
  { id: '97', queries: ['exoplanet NASA', 'starfield space'] },
  { id: '98', queries: ['PlayStation controller', 'game controller'] },
  { id: '99', queries: ['neon signs night city', 'neon night'] },
  { id: '100', queries: ['cinematography camera', 'film camera'] },
  { id: '101', queries: ['IMAX cinema', 'cinema projector'] },
  { id: '102', queries: ['Rosette Nebula', 'nebula red space'] },
  { id: '103', queries: ['spacecraft NASA', 'space probe'] },
  { id: '104', queries: ['fire flames', 'bonfire flames'] },
  { id: '105', queries: ['gas station night', 'petrol station'] },
];
