const fs = require('fs');
const path = 'lib/articles.ts';
let t = fs.readFileSync(path, 'utf8');
const idx = t.lastIndexOf('];');
if (idx === -1) { console.error('EOF'); process.exit(1); }
const A = [];
const cat = (id, slug, name, desc, color) => ({ id, slug, name, description: desc, color });
const src = (title, url, type) => ({ title, url, type });

// TECNOLOGIA
// TECNOLOGIA
A.push({ id:'108', slug:'edge-computinge-processamento-de-dados', title:'Edge Computing: Como o Processamento de Dados na Borda da Rede Está Mudando a Tecnologia', excerpt:'O edge computing aproxima o processamento de dados de onde eles são gerados, reduzindo latência e uso de banda.', content:'<h2>O Que é Edge Computing?</h2><p>Edge computing é um paradigma de computação distribuída que consiste em processar dados o mais próximo possível de onde eles são gerados — na "borda" da rede — em vez de enviá-los para data centers distantes. Isso reduz a latência, economiza banda e melhora a confiabilidade de aplicações que exigem respostas em tempo real.</p><h2>Como Funciona na Prática?</h2><p>Em vez de enviar dados de um sensor industrial para um servidor na nuvem a milhares de quilômetros, o edge computing processa esses dados localmente, em um servidor ou gateway próximo. Apenas os resultados agregados ou anomalias são enviados para a nuvem.</p><h3>Aplicações Principais</h3><p>Veículos autônomos usam edge computing para processar dados de câmeras e sensores em tempo real. Na Internet das Coisas (IoT) industrial, sensores monitoram máquinas e previnem falhas. Cidades inteligentes usam a tecnologia para gerenciar semáforos e fluxo de tráfego.</p><h2>Benefícios e Desafios</h2><p>Os principais benefícios são: redução de latência, economia de banda e maior resiliência. Os desafios incluem gerenciar milhares de dispositivos distribuídos, garantir segurança em cada nó e manter software atualizado em escala.</p><h2>O Futuro do Edge Computing</h2><p>Com o 5G e a expansão da IoT, o edge computing deve se tornar ainda mais relevante. A combinação com inteligência artificial — chamada "AI on the Edge" — permitirá que dispositivos tomem decisões complexas localmente.</p>', category: cat('tecnologia','tecnologia','Tecnologia','Gadgets, computação, cibersegurança, robótica e tecnologia futura','#06b6d4'), tags:['edge computing','IoT','latência','5G','nuvem','tempo real'], author:{id:'1',name:'Equipe NexoraComic'}, publishedAt:'2026-09-10', readingTime:8, featuredImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Edge_computing_architecture.png/800px-Edge_computing_architecture.png', imageAlt:'Diagrama mostrando a arquitetura de edge computing', sources:[src('Wikipedia — Edge computing','https://en.wikipedia.org/wiki/Edge_computing','other'),src('Wikipedia — Fog computing','https://en.wikipedia.org/wiki/Fog_computing','other')] });

A.push({ id:'109', slug:'tpu-tensor-processing-unit-google-ia', title:'TPU: Os Chips Especializados do Google que Aceleram o Treinamento de Inteligência Artificial', excerpt:'O Tensor Processing Unit (TPU) é um chip projetado especificamente para cargas de trabalho de machine learning.', content:'<h2>O Que é um TPU?</h2><p>O Tensor Processing Unit (TPU) é um circuito integrado específico para aplicação (ASIC) desenvolvido pelo Google para acelerar tarefas de redes neurais e machine learning. Diferente de processadores generalistas (CPUs) ou gráficos (GPUs), o TPU foi projetado do zero para operações de matriz que são a base do treinamento e inferência de modelos de IA.</p><h2>Como Ele se Compara a uma GPU?</h2><p>Enquanto GPUs são excelentes para processamento paralelo, os TPUs são otimizados para alta precisão em operações de multiplicação de matrizes com baixa precisão numérica (8 bits ou menos). Isso permite mais operações por joule de energia.</p><h3>Gerações e Evolução</h3><p>O Google começou a usar TPUs internamente em 2015 e os disponibilizou para terceiros em 2018 via Google Cloud. Desde então, o hardware evoluiu por múltiplas gerações.</p><h2>Por Que Isso Importa?</h2><p>Treinar grandes modelos de linguagem requer milhares de chips trabalhando em paralelo por semanas. A especialização do TPU reduz o custo energético e o tempo de treinamento.</p><h3>Limitações</h3><p>TPUs são menos flexíveis que GPUs: são otimizados para cargas de trabalho específicas de machine learning e não servem para renderização gráfica.</p><h2>O Futuro dos Aceleradores de IA</h2><p>Outras empresas desenvolveram seus próprios aceleradores: a Microsoft tem o Maia, a Amazon o Trainium e Inferentia.</p>', category: cat('tecnologia','tecnologia','Tecnologia','Gadgets, computação, cibersegurança, robótica e tecnologia futura','#06b6d4'), tags:['TPU','Google','machine learning','GPU','acelerador de IA','hardware'], author:{id:'1',name:'Equipe NexoraComic'}, publishedAt:'2026-09-10', readingTime:8, featuredImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Google_TPU_v1.jpg/800px-Google_TPU_v1.jpg', imageAlt:'Foto de um chip TPU do Google', sources:[src('Wikipedia — Tensor Processing Unit','https://en.wikipedia.org/wiki/Tensor_Processing_Unit','other'),src('Wikipedia — AI accelerator','https://en.wikipedia.org/wiki/AI_accelerator','other')] });
// ESPAÇO
A.push({ id:'110', slug:'aurora-boreais-ciencia-luzes-do-norte', title:'Aurora Boreal: A Ciência por Trás das Luzes do Norte que Encantam a Humanidade', excerpt:'As auroras boreais são causadas pela interação de partículas solares com o campo magnético da Terra.', content:'<h2>O Que Causa as Auroras?</h2><p>As auroras são causadas por partículas carregadas do vento solar (principalmente elétrons e prótons) que colidem com átomos da atmosfera terrestre. Essas partículas são canalizadas pelo campo magnético da Terra em direção aos polos, onde a proteção magnética é menor.</p><h2>Por Que as Auroras Têm Cores Diferentes?</h2><p>A cor da aurora depende do elemento atingido e da altitude. O oxigênio emite luz verde (a mais comum) em altitudes de 100-300 km e vermelho acima de 300 km. O nitrogênio produz tons de azul e roxo.</p><h3>A Conexão com Tempestades Solares</h3><p>Durante tempestades solares, as auroras se intensificam e podem ser vistas em latitudes mais baixas. O Evento Carrington de 1859 produziu auroras visíveis no Caribe.</p><h2>Por Que Isso Importa?</h2><p>Além da beleza, as auroras são um indicador visível da atividade solar. Tempestades solares intensas podem danificar satélites, interromper comunicações e redes elétricas.</p><h3>Limitações e Incertezas</h3><p>Prever auroras com precisão ainda é difícil. Dependemos de satélites que monitoram o vento solar, dando apenas 15-60 minutos de aviso.</p><h2>Onde e Quando Ver Auroras?</h2><p>As auroras são mais visíveis nos meses de inverno, em regiões de alta latitude: Noruega, Suécia, Finlândia, Islândia, Canadá e Alasca.</p>', category: cat('espaco','espaco','Espaço','Astronomia, NASA, planetas, estrelas e missões espaciais','#f59e0b'), tags:['aurora boreal','vento solar','campo magnético','tempestade solar','atmosfera','NASA'], author:{id:'1',name:'Equipe NexoraComic'}, publishedAt:'2026-09-10', readingTime:8, featuredImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Aurora_boreal_-_panoramio.jpg/800px-Aurora_boreal_-_panoramio.jpg', imageAlt:'Fotografia de uma aurora boreal verde sobre paisagem nevada', sources:[src('Wikipedia — Aurora','https://en.wikipedia.org/wiki/Aurora','other'),src('Wikipedia — Solar wind','https://en.wikipedia.org/wiki/Solar_wind','other')] });

A.push({ id:'111', slug:'europa-clipper-missao-nasa-lua-jupiter', title:'Europa Clipper: A Missão da NASA que Vai Buscar Vida na Lua de Júpiter', excerpt:'A missão Europa Clipper, lançada em 2024, vai investigar a lua Europa de Júpiter, que abriga um oceano subterrâneo.', content:'<h2>Por Que Europa?</h2><p>Europa, uma das luas galileanas de Júpiter, é considerada um dos lugares mais promissores do Sistema Solar para buscar vida. Sob sua crosta de gelo existe um oceano global de água líquida que pode conter o dobro de água de todos os oceanos da Terra combinados.</p><h2>O Que a Europa Clipper Vai Fazer?</h2><p>A missão, lançada em outubro de 2024, vai orbitar Júpiter e realizar 49 aproximações próximas a Europa ao longo de 4 anos. Cada aproximação vai mapear a superfície com câmeras de alta resolução e medir a espessura da crosta de gelo.</p><h3>Instrumentos a Bordo</h3><p>A nave carrega 9 instrumentos: câmeras, radar de penetração de gelo, espectrômetros e magnetômetro para confirmar a existência e profundidade do oceano subterrâneo.</p><h2>Por Que Isso Importa?</h2><p>Se a Europa Clipper encontrar condições habitáveis — água líquida, fontes de energia e moléculas orgânicas — isso não significa que existe vida, mas que os ingredientes estão lá.</p><h3>Desafios da Missão</h3><p>A radiação de Júpiter é intensa: a nave recebe cerca de 40 milhões de rads durante a missão, o que exigiu componentes eletrônicos resistentes.</p><h2>O Que Esperar dos Resultados</h2><p>Os primeiros dados científicos devem chegar em 2025. A missão completa vai durar até 2028 ou mais.</p>', category: cat('espaco','espaco','Espaço','Astronomia, NASA, planetas, estrelas e missões espaciais','#f59e0b'), tags:['Europa Clipper','NASA','Júpiter','Europa','vida extraterrestre','oceano subterrâneo'], author:{id:'1',name:'Equipe NexoraComic'}, publishedAt:'2026-09-10', readingTime:9, featuredImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Europa_Clipper_spacecraft_model.png/800px-Europa_Clipper_spacecraft_model.png', imageAlt:'Modelo da nave Europa Clipper da NASA', sources:[src('Wikipedia — Europa Clipper','https://en.wikipedia.org/wiki/Europa_Clipper','other'),src('Wikipedia — Europa (lua)','https://en.wikipedia.org/wiki/Europa_(moon)','other')] });
// INTELIGÊNCIA ARTIFICIAL
A.push({ id:'112', slug:'agentes-autonomos-ia-tomada-de-decisao', title:'Agentes Autônomos de IA: Sistemas que Tomam Decisões Sem Intervenção Humana', excerpt:'Os agentes autônomos de IA vão além dos chatbots: são sistemas que percebem o ambiente, planejam ações e executam tarefas complexas sozinhos.', content:'<h2>O Que é um Agente Autônomo?</h2><p>Um agente autônomo de IA é um sistema que, dado um objetivo, é capaz de perceber seu ambiente, tomar decisões e executar ações para atingir esse objetivo sem intervenção humana constante.</p><h2>Como Funcionam?</h2><p>A arquitetura típica combina um modelo de linguagem com ferramentas externas: acesso à internet, capacidade de executar código, memória de longo prazo e APIs de serviços.</p><h3>Aplicações Práticas</h3><p>Já existem agentes para: pesquisa acadêmica, desenvolvimento de software, atendimento ao cliente e finanças. A OpenAI, Anthropic e Google estão investindo pesadamente nessa direção.</p><h2>Riscos e Desafios</h2><p>A autonomia traz riscos: um agente pode tomar decisões erradas em cascata, acessar informações sensíveis ou ser manipulado por instruções maliciosas.</p><h3>Limitações Atuais</h3><p>Os agentes atuais ainda cometem erros frequentes, especialmente em tarefas longas que exigem planejamento de muitos passos.</p><h2>O Futuro dos Agentes</h2><p>A tendência é que os agentes se tornem mais capazes e confiáveis, com melhorias em raciocínio, memória e verificação de fatos.</p>', category: cat('inteligencia-artificial','inteligencia-artificial','Inteligência Artificial','IA generativa, ferramentas de IA, pesquisa e futuro da IA','#ec4899'), tags:['agentes autônomos','IA','automação','tomada de decisão','OpenAI','Anthropic'], author:{id:'1',name:'Equipe NexoraComic'}, publishedAt:'2026-09-10', readingTime:9, featuredImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/AI_agent_architecture.png/800px-AI_agent_architecture.png', imageAlt:'Diagrama mostrando a arquitetura de um agente autônomo de IA', sources:[src('Wikipedia — Agentic AI','https://en.wikipedia.org/wiki/Agentic_AI','other'),src('Wikipedia — Autonomous agent','https://en.wikipedia.org/wiki/Autonomous_agent','other')] });

A.push({ id:'113', slug:'modelos-multimodais-ia-texto-imagem-audio', title:'Modelos Multimodais: A IA que Entende Texto, Imagem e Áudio Simultaneamente', excerpt:'Os modelos multimodais representam um salto na inteligência artificial, permitindo que um único sistema processe e relacione diferentes tipos de dados.', content:'<h2>O Que São Modelos Multimodais?</h2><p>Modelos multimodais são sistemas de IA capazes de processar e relacionar múltiplos tipos de dados — texto, imagens, áudio, vídeo — simultaneamente.</p><h2>Como Funcionam?</h2><p>A arquitetura típica usa codificadores especializados para cada modalidade que mapeiam os dados para um espaço vetorial compartilhado, onde conceitos similares ficam próximos.</p><h3>Exemplos de Modelos Multimodais</h3><p>O GPT-4V da OpenAI aceita imagens como entrada. O Gemini do Google foi projetado desde o início para ser multimodal. O DALL-E gera imagens a partir de texto.</p><h2>Aplicações Práticas</h2><p>As aplicações são vastas: sistemas de busca que combinam texto e imagem, assistentes para pessoas com deficiência visual, análise de vídeos e educação.</p><h3>Desafios e Limitações</h3><p>Treinar modelos multimodais requer enormes volumes de dados pareados. A alucinação também é um problema: o modelo pode descrever objetos que não estão na imagem.</p><h2>O Futuro da IA Multimodal</h2><p>A tendência é que os modelos se tornem cada vez mais integrados, processando não apenas texto, imagem e áudio, mas também dados de sensores e sinais biológicos.</p>', category: cat('inteligencia-artificial','inteligencia-artificial','Inteligência Artificial','IA generativa, ferramentas de IA, pesquisa e futuro da IA','#ec4899'), tags:['multimodal','IA','GPT-4V','Gemini','visão computacional','processamento de áudio'], author:{id:'1',name:'Equipe NexoraComic'}, publishedAt:'2026-09-10', readingTime:9, featuredImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Multimodal_AI_architecture.png/800px-Multimodal_AI_architecture.png', imageAlt:'Diagrama mostrando a arquitetura de um modelo multimodal de IA', sources:[src('Wikipedia — Multimodal learning','https://en.wikipedia.org/wiki/Multimodal_learning','other'),src('Wikipedia — Vision-language model','https://en.wikipedia.org/wiki/Vision_language_model','other')] });
// FUTURO
A.push({ id:'114', slug:'biologia-sintetica-criando-organismos-artificiais', title:'Biologia Sintética: A Ciência que Projeta e Constrói Organismos Vivos do Zero', excerpt:'A biologia sintética combina engenharia e biologia para criar organismos com funções novas.', content:'<h2>O Que é Biologia Sintética?</h2><p>A biologia sintética é um campo interdisciplinar que aplica princípios de engenharia à biologia, com o objetivo de projetar e construir novas partes biológicas, dispositivos e sistemas.</p><h2>Como os Cientistas "Programam" DNA?</h2><p>Os pesquisadores usam sequências de DNA como "código" para instruir células a produzir proteínas específicas ou a responder a estímulos ambientais.</p><h3>Aplicações em Medicina</h3><p>A artemisinina (antimalárico) já é produzida por leveduras geneticamente modificadas. Células imunológicas sintéticas estão sendo desenvolvidas para atacar tumores.</p><h2>Aplicações Ambientais</h2><p>A biologia sintética é usada para criar organismos que degradam plásticos, capturam carbono ou produzem biocombustíveis.</p><h3>Dilemas Éticos e de Segurança</h3><p>A possibilidade de criar patógenos sintéticos gera debates sobre biossegurança. A comunidade científica adotou práticas de "biocontenção".</p><h2>O Futuro da Biologia Sintética</h2><p>A longo prazo, pode permitir a criação de órgãos artificiais para transplante e materiais autorreparáveis.</p>', category: cat('futuro','futuro','Futuro','Tecnologias emergentes, biotecnologia, energia e cidades inteligentes','#10b981'), tags:['biologia sintética','DNA sintético','engenharia genética','biossegurança','biotecnologia'], author:{id:'1',name:'Equipe NexoraComic'}, publishedAt:'2026-09-10', readingTime:9, featuredImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Synthetic_biology_diagram.png/800px-Synthetic_biology_diagram.png', imageAlt:'Diagrama mostrando o ciclo de projeto-construção-teste da biologia sintética', sources:[src('Wikipedia — Synthetic biology','https://en.wikipedia.org/wiki/Synthetic_biology','other'),src('Wikipedia — Genetic circuit','https://en.wikipedia.org/wiki/Genetic_circuit','other')] });

A.push({ id:'115', slug:'energia-solar-espacial-paineis-orbita', title:'Energia Solar Espacial: A Ideia de Captar Luz do Sol no Espaço e Transmiti-la para a Terra', excerpt:'A energia solar espacial propõe captar luz solar em órbita e transmiti-la para a Terra via micro-ondas.', content:'<h2>O Conceito</h2><p>A energia solar espacial (SBSP) propõe colocar painéis solares em órbita geoestacionária (36.000 km de altitude), onde o sol brilha 24 horas por dia sem interferência da atmosfera, e transmitir a energia gerada para a Terra via feixes de micro-ondas.</p><h2>Por Que no Espaço é Melhor?</h2><p>Painéis solares no espaço recebem cerca de 30% mais energia que na superfície, pois não há atmosfera para absorver ou dispersar a luz.</p><h3>Desafios Técnicos</h3><p>O principal obstáculo é o custo de lançamento. A montagem de estruturas gigantescas no espaço exigiria robótica avançada ou presença humana.</p><h2>Quem Está Investindo?</h2><p>A China planeja testar um sistema até 2030. A ESA tem o programa SOLARIS. A Caltech demonstrou o MAPLE em 2023, que transmitiu energia detectável do espaço para a Terra.</p><h3>Limitações e Incertezas</h3><p>A energia solar espacial provavelmente não será competitiva com energia solar terrestre nas próximas décadas.</p><h2>O Futuro da Energia Solar Espacial</h2><p>Se os custos de lançamento continuarem caindo e a montagem robótica no espaço avançar, pode se tornar viável para aplicações específicas.</p>', category: cat('futuro','futuro','Futuro','Tecnologias emergentes, biotecnologia, energia e cidades inteligentes','#10b981'), tags:['energia solar espacial','SBSP','órbita geoestacionária','transmissão de energia','ESA','SpaceX'], author:{id:'1',name:'Equipe NexoraComic'}, publishedAt:'2026-09-10', readingTime:9, featuredImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Solar_power_satellite.jpg/800px-Solar_power_satellite.jpg', imageAlt:'Ilustração de um satélite de energia solar espacial', sources:[src('Wikipedia — Space-based solar power','https://en.wikipedia.org/wiki/Space-based_solar_power','other'),src('Wikipedia — Solar power satellite','https://en.wikipedia.org/wiki/Solar_power_satellite','other')] });
// GAMES
A.push({ id:'116', slug:'geracao-procedural-mundo-aberto-games', title:'Geração Procedural: Como Algoritmos Criam Mundos Infinitos nos Games', excerpt:'A geração procedural permite que jogos criem mundos vastos e únicos sem que artistas modelem cada árvore manualmente.', content:'<h2>O Que é Geração Procedural?</h2><p>Geração procedural é o uso de algoritmos para criar conteúdo automaticamente, em vez de produzi-lo manualmente. Em games, isso pode significar terrenos, níveis, missões ou itens gerados por código.</p><h2>Como Funciona na Prática?</h2><p>O método mais comum usa funções de ruído (como Perlin noise) para gerar terrenos. Regras adicionais determinam onde colocar vegetação, rios ou cidades.</p><h3>Exemplos Famosos</h3><p>Minecraft é o exemplo mais conhecido. No Man\'s Sky usa geração procedural para criar 18 quintilhões de planetas. Spelunky e Hades geram níveis proceduralmente.</p><h2>Benefícios e Desafios</h2><p>A principal vantagem é a rejogabilidade. O desafio é garantir que o conteúdo gerado faça sentido e seja jogável.</p><h3>O Papel da IA</h3><p>A inteligência artificial está sendo usada para melhorar a geração procedural, com modelos de linguagem gerando diálogos e missões coerentes.</p><h2>O Futuro da Geração Procedural</h2><p>A tendência é que a geração procedural se torne mais sofisticada, com algoritmos que entendem contexto e narrativa.</p>', category: cat('games','games','Games','Notícias de games, tecnologia por trás dos jogos e análise da indústria','#ef4444'), tags:['geração procedural','Minecraft','algoritmos','mundo aberto','aleatoriedade'], author:{id:'1',name:'Equipe NexoraComic'}, publishedAt:'2026-09-10', readingTime:8, featuredImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Minecraft_world_example.png/800px-Minecraft_world_example.png', imageAlt:'Captura de tela de um mundo gerado proceduralmente em Minecraft', sources:[src('Wikipedia — Procedural generation','https://en.wikipedia.org/wiki/Procedural_generation','other'),src('Wikipedia — Procedural generation in video games','https://en.wikipedia.org/wiki/Procedural_generation_in_video_games','other')] });

A.push({ id:'117', slug:'acessibilidade-games-jogadores-deficiencia', title:'Acessibilidade em Games: As Tecnologias que Estão Incluindo Jogadores com Deficiência', excerpt:'A indústria de games está investindo em recursos de acessibilidade que permitem que pessoas com deficiência visual, auditiva ou motora joguem.', content:'<h2>Por Que Acessibilidade em Games Importa?</h2><p>Cerca de 400 milhões de jogadores no mundo têm algum tipo de deficiência. A indústria tem reconhecido que acessibilidade não é um recurso opcional, mas um direito.</p><h2>Inovações para Deficiência Visual</h2><p>Jogos como The Last of Us Part II oferecem modos de alto contraste, narração de menus e cenas, indicadores sonoros direcionais e fontes em tamanho ajustável.</p><h3>Inovações para Deficiência Auditiva</h3><p>Fortnite e Apex Legends têm indicadores visuais de direção de passos e tiros. The Last of Us Part II mostra a direção de sons na tela.</p><h2>Inovações para Deficiência Motora</h2><p>O Xbox Adaptive Controller é um hub que permite conectar dispositivos externos para pessoas com mobilidade limitada.</p><h3>O Papel da Comunidade</h3><p>Organizações como a AbleGamers e Game Accessibility Guidelines criaram diretrizes para desenvolvedores.</p><h2>O Futuro da Acessibilidade em Games</h2><p>A inteligência artificial promete avanços: transcrição de voz em tempo real, descrição automática de cenas e controles adaptativos.</p>', category: cat('games','games','Games','Notícias de games, tecnologia por trás dos jogos e análise da indústria','#ef4444'), tags:['acessibilidade','deficiência','Xbox Adaptive Controller','inclusão','game design'], author:{id:'1',name:'Equipe NexoraComic'}, publishedAt:'2026-09-10', readingTime:9, featuredImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Xbox_Adaptive_Controller.jpg/800px-Xbox_Adaptive_Controller.jpg', imageAlt:'Foto do Xbox Adaptive Controller', sources:[src('Wikipedia — Game accessibility','https://en.wikipedia.org/wiki/Game_accessibility','other'),src('Wikipedia — Xbox Adaptive Controller','https://en.wikipedia.org/wiki/Xbox_Adaptive_Controller','other')] });
// FILMES E SÉRIES
A.push({ id:'118', slug:'preservacao-digital-filmes-antigos-restauracao', title:'Preservação Digital de Filmes: Como a Tecnologia Está Salvando Clássicos da Deterioração', excerpt:'Milhares de filmes antigos estão se deteriorando em arquivos físicos. A preservação digital usa scanners de alta resolução e IA para restaurar e proteger o cinema clássico.', content:'<h2>O Problema da Deterioração</h2><p>Estima-se que 50% dos filmes produzidos antes de 1950 estejam perdidos para sempre. Filmes em nitrato de celulose são altamente inflamáveis e se decompõem com o tempo.</p><h2>Como Funciona a Preservação Digital?</h2><p>O processo começa com a limpeza física do filme e reparo de danos. Em seguida, o filme é digitalizado em scanners de alta resolução (4K, 6K ou até 8K).</p><h3>O Papel da Inteligência Artificial</h3><p>A IA pode reconstruir quadros faltantes, aumentar a resolução de filmes antigos e até colorir filmes em preto e branco de forma historicamente precisa.</p><h2>Arquivos e Instituições</h2><p>Instituições como a Library of Congress, a Cinemateca Francesa e o BFI mantêm acervos e realizam restaurações.</p><h3>Desafios e Limitações</h3><p>Formatos digitais também se tornam obsoletos. A migração periódica para novos formatos é necessária.</p><h2>O Futuro da Preservação</h2><p>A digitalização em nuvem e o armazenamento distribuído reduzem o risco de perda. A meta é que nenhum filme clássico seja perdido para sempre.</p>', category: cat('filmes-series','filmes-series','Filmes e Séries','Ficção científica, tecnologia no cinema e análise de produções','#f97316'), tags:['preservação digital','restauração de filmes','cinema clássico','IA','arquivos','Library of Congress'], author:{id:'1',name:'Equipe NexoraComic'}, publishedAt:'2026-09-10', readingTime:9, featuredImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Film_restoration_scanner.jpg/800px-Film_restoration_scanner.jpg', imageAlt:'Scanner de restauração de filmes em alta resolução', sources:[src('Wikipedia — Film preservation','https://en.wikipedia.org/wiki/Film_preservation','other'),src('Wikipedia — Digital restoration','https://en.wikipedia.org/wiki/Digital_restoration','other')] });

A.push({ id:'119', slug:'deepfake-cinema-rostos-sinteticos-impacto', title:'Deepfake no Cinema: Como a Tecnologia de Rostos Sintéticos Está Mudando a Indústria', excerpt:'A tecnologia deepfake permite substituir rostos em vídeos com realismo impressionante. No cinema, é usada para rejuvenescer atores e criar dublês digitais.', content:'<h2>O Que é Deepfake?</h2><p>Deepfake é uma técnica de inteligência artificial que usa redes neurais para substituir o rosto de uma pessoa em um vídeo pelo de outra, mantendo expressões faciais e movimentos.</p><h2>Aplicações no Cinema</h2><p>A indústria cinematográfica adotou deepfakes para rejuvenescer atores, completar cenas de atores falecidos e criar dublês digitais para cenas de risco.</p><h3>O Caso de Star Wars e Outros Exemplos</h3><p>Em Rogue One, uma versão digital de Peter Cushing interpretou o Grand Moff Tarkin. Em The Irishman, Martin Scorsese usou "de-aging" digital.</p><h2>Questões Éticas e Legais</h2><p>O uso de deepfake levanta questões sobre consentimento. A SAG-AFTRA negociou que o uso de réplicas digitais exige consentimento e compensação.</p><h3>Regulamentação e Detecção</h3><p>Países como China e EUA aprovaram leis exigindo que deepfakes sejam rotulados como tal.</p><h2>O Futuro dos Deepfakes no Cinema</h2><p>A tendência é que a tecnologia se torne mais acessível e realista, permitindo que atores "atuem" em filmes décadas após sua morte.</p>', category: cat('filmes-series','filmes-series','Filmes e Séries','Ficção científica, tecnologia no cinema e análise de produções','#f97316'), tags:['deepfake','cinema','IA','de-aging','Star Wars','ética digital'], author:{id:'1',name:'Equipe NexoraComic'}, publishedAt:'2026-09-10', readingTime:9, featuredImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Deepfake_example.jpg/800px-Deepfake_example.jpg', imageAlt:'Exemplo de deepfake mostrando substituição de rosto em vídeo', sources:[src('Wikipedia — Deepfake','https://en.wikipedia.org/wiki/Deepfake','other'),src('Wikipedia — Digital likeness','https://en.wikipedia.org/wiki/Digital_likeness','other')] });
// QUADRINHOS
A.push({ id:'120', slug:'webcomics-quadrinhos-digitais-revolucao', title:'Webcomics e Quadrinhos Digitais: Como as Plataformas Online Estão Reinventando a Forma de Publicar HQs', excerpt:'As webcomics e plataformas digitais democratizaram a publicação de quadrinhos, permitindo que artistas independentes alcancem milhões de leitores.', content:'<h2>O Que São Webcomics?</h2><p>Webcomics são quadrinhos publicados diretamente na internet, em vez de em revistas impressas. O formato varia: tiras curtas, graphic novels serializadas ou "webtoons" (quadrinhos verticais otimizados para celular).</p><h2>Plataformas e Modelos de Negócio</h2><p>Plataformas como Webtoon, Tapas e Global Comix oferecem infraestrutura para artistas publicarem e monetizarem seu trabalho.</p><h3>Exemplos de Sucesso</h3><p>Homestuck acumulou mais de 800.000 leitores diários no auge. Lore Olympus foi lido por mais de 5 milhões de pessoas e ganhou uma adaptação para TV.</p><h2>Vantagens e Desafios</h2><p>A principal vantagem é a liberdade criativa. Os desafios incluem concorrência intensa e a pressão por atualização constante.</p><h3>O Impacto nas Editoras Tradicionais</h3><p>Editoras como Marvel e DC agora digitalizam seus catálogos e oferecem assinaturas digitais.</p><h2>O Futuro dos Quadrinhos Digitais</h2><p>A tendência mais sólida é a integração entre mídias: webcomics que viram animações, jogos ou séries.</p>', category: cat('quadrinhos','quadrinhos','Quadrinhos','Comics, super-heróis, ciência nos quadrinhos e adaptações','#6366f1'), tags:['webcomics','webtoons','quadrinhos digitais','Webtoon','Tapas','artistas independentes'], author:{id:'1',name:'Equipe NexoraComic'}, publishedAt:'2026-09-10', readingTime:9, featuredImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Webtoon_example.jpg/800px-Webtoon_example.jpg', imageAlt:'Captura de tela de um webcomic digital no formato webtoon', sources:[src('Wikipedia — Webcomic','https://en.wikipedia.org/wiki/Webcomic','other'),src('Wikipedia — Webtoon','https://en.wikipedia.org/wiki/Webtoon','other')] });

A.push({ id:'121', slug:'representacao-diversidade-quadrinhos-evolucao', title:'Representação e Diversidade nos Quadrinhos: Como a Indústria Está Evoluindo para Incluir Todos os Leitores', excerpt:'Os quadrinhos historicamente foram dominados por personagens brancos e masculinos. Nas últimas décadas, a indústria tem se esforçado para incluir mais diversidade.', content:'<h2>A História da Representação nos Quadrinhos</h2><p>Durante décadas, os quadrinhos mainstream foram dominados por personagens brancos, heterossexuais e masculinos. Mulheres apareciam principalmente como interesses românticos.</p><h2>A Mudança Começa</h2><p>A partir dos anos 1970, personagens como Tempestade, Pantera Negra e Luke Cage trouxeram mais diversidade. Nos anos 2010, a diversidade se tornou uma prioridade editorial.</p><h3>Marcos Recentes</h3><p>Kamala Khan tornou-se a primeira personagem muçulmana a ter sua própria série na Marvel. Miles Morales ganhou destaque e foi protagonista do filme Spider-Verse.</p><h2>Por Que a Diversidade Importa?</h2><p>Representação importa porque molda como nos vemos e como vemos os outros. Crianças que crescem vendo heróis que se parecem com elas desenvolvem autoestima.</p><h3>Desafios e Críticas</h3><p>A diversidade enfrenta resistência de uma parcela do público. A representação precisa ser autêntica.</p><h2>O Futuro da Representação</h2><p>A tendência é que a diversidade se torne a norma, não a exceção.</p>', category: cat('quadrinhos','quadrinhos','Quadrinhos','Comics, super-heróis, ciência nos quadrinhos e adaptações','#6366f1'), tags:['diversidade','representação','Ms. Marvel','Miles Morales','LGBTQIA+','inclusão'], author:{id:'1',name:'Equipe NexoraComic'}, publishedAt:'2026-09-10', readingTime:9, featuredImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Diverse_superheroes.jpg/800px-Diverse_superheroes.jpg', imageAlt:'Ilustração mostrando diversos super-heróis de diferentes etnias e gêneros', sources:[src('Wikipedia — Representation in comics','https://en.wikipedia.org/wiki/Representation_in_comics','other'),src('Wikipedia — Diversity in comic books','https://en.wikipedia.org/wiki/Diversity_in_comic_books','other')] });
// CURIOSIDADES
A.push({ id:'122', slug:'ilusoes-opticas-cerebro-enganado', title:'Ilusões de Óptica e o Cérebro: Como Nossa Mente é Enganada por Imagens que Não São o Que Parecem', excerpt:'As ilusões de óptica revelam como o cérebro interpreta (e muitas vezes distorce) a realidade visual.', content:'<h2>O Que São Ilusões de Óptica?</h2><p>Ilusões de óptica são imagens ou padrões que enganam o cérebro, fazendo-nos ver algo que não está lá ou interpretar incorretamente o que vemos.</p><h2>Tipos de Ilusões</h2><p>Existem três categorias principais: ilusões literais, ilusões fisiológicas e ilusões cognitivas.</p><h3>A Ciência por Trás do Engano</h3><p>O cérebro processa informações visuais em múltiplas etapas, fazendo "palpites" baseados em heurísticas. As ilusões exploram essas heurísticas.</p><h2>Por Que Isso Importa?</h2><p>Estudar ilusões ajuda cientistas a entender como a percepção visual funciona e como pode falhar.</p><h3>Ilusões Famosas</h3><p>A grade de Hermann, o triângulo de Kanizsa e a ilusão de Müller-Lyer são exemplos clássicos.</p><h2>O Futuro do Estudo das Ilusões</h2><p>A realidade virtual permite criar ilusões impossíveis no mundo real, ajudando pesquisadores a estudar percepção em ambientes controlados.</p>', category: cat('curiosidades','curiosidades','Curiosidades','Ciência fascinante, tecnologia histórica e descobertas incomuns','#14b8a6'), tags:['ilusões de óptica','percepção visual','neurociência','cognição','psicologia'], author:{id:'1',name:'Equipe NexoraComic'}, publishedAt:'2026-09-10', readingTime:8, featuredImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Müller-Lyer_illusion.svg/800px-Müller-Lyer_illusion.svg.png', imageAlt:'Ilustração da ilusão de Müller-Lyer', sources:[src('Wikipedia — Optical illusion','https://en.wikipedia.org/wiki/Optical_illusion','other'),src('Wikipedia — Optical illusion types','https://en.wikipedia.org/wiki/Optical_illusion_types','other')] });

A.push({ id:'123', slug:'animais-que-usam-ferramentas-inteligencia', title:'Animais que Usam Ferramentas: A Inteligência Surpreendente de Espécies Além dos Humanos', excerpt:'O uso de ferramentas, considerado exclusivo dos humanos, é observado em diversas espécies: chimpanzés, corvos, polvos e até formigas.', content:'<h2>O Que é Uso de Ferramentas?</h2><p>Uso de ferramentas é definido como o emprego de um objeto externo para atingir um objetivo — como usar uma vara para extrair cupins ou uma pedra para quebrar uma noz.</p><h2>Exemplos Notáveis</h2><p>Chimpanzés usam pedras como martelos e varas para "pescar" cupins. Corvos-da-Nova-Caledônia fabricam ganchos de galhos. Polvos-do-coco carregam cascas de coco para usar como abrigo.</p><h3>Inteligência e Cultura Animal</h3><p>O uso de ferramentas não é apenas instintivo: muitas espécies aprendem observando outros, o que constitui uma forma de cultura.</p><h2>Por Que Isso Importa?</h2><p>Descobrir que outros animais usam ferramentas desafia a ideia de que humanos são únicos em inteligência.</p><h3>Limitações e Incertezas</h3><p>Definir "inteligência" é controverso. Uso de ferramentas é um indicador, mas não o único.</p><h2>O Futuro da Pesquisa</h2><p>Câmeras de monitoramento remoto e inteligência artificial estão permitindo observar animais em seus habitats naturais sem interferência humana.</p>', category: cat('curiosidades','curiosidades','Curiosidades','Ciência fascinante, tecnologia histórica e descobertas incomuns','#14b8a6'), tags:['animais','ferramentas','inteligência animal','chimpanzés','corvos','polvos'], author:{id:'1',name:'Equipe NexoraComic'}, publishedAt:'2026-09-10', readingTime:9, featuredImage:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Chimpanzee_using_tool.jpg/800px-Chimpanzee_using_tool.jpg', imageAlt:'Foto de um chimpanzé usando uma vara para extrair cupins', sources:[src('Wikipedia — Tool use by animals','https://en.wikipedia.org/wiki/Tool_use_by_animals','other'),src('Wikipedia — Tool use by non-human animals','https://en.wikipedia.org/wiki/Tool_use_by_non-human_animals','other')] });

// Serialize and insert
const serialize = (a) => {
  let s = '';
  a.forEach((art) => {
    s += '  {\n';
    s += `    id: '${art.id}',\n`;
    s += `    slug: '${art.slug}',\n`;
    s += `    title: '${art.title.replace(/'/g,"\\'")}',\n`;
    s += `    excerpt: '${art.excerpt.replace(/'/g,"\\'")}',\n`;
    s += `    content: \`${art.content}\`,\n`;
    s += `    category: { id: '${art.category.id}', slug: '${art.category.slug}', name: '${art.category.name}', description: '${art.category.description}', color: '${art.category.color}' },\n`;
    s += `    tags: [${art.tags.map(t => `'${t}'`).join(', ')}],\n`;
    s += `    author: { id: '${art.author.id}', name: '${art.author.name}' },\n`;
    s += `    publishedAt: '${art.publishedAt}',\n`;
    s += `    readingTime: ${art.readingTime},\n`;
    s += `    featuredImage: '${art.featuredImage}',\n`;
    s += `    imageAlt: '${art.imageAlt.replace(/'/g,"\\'")}',\n`;
    s += `    sources: [\n`;
    art.sources.forEach(src => {
      s += `      { title: '${src.title.replace(/'/g,"\\'")}', url: '${src.url}', type: '${src.type}' },\n`;
    });
    s += `    ]\n`;
    s += '  },\n';
  });
  return s;
};

t = t.slice(0, idx) + '\n' + serialize(A) + '\n];\n';
fs.writeFileSync(path, t);
console.log('OK articles=' + A.length + ' total_len=' + t.length);









